# Generated by Django 4.2.2 on 2023-07-02 17:22

import apps.tools.database_operations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
