# Generated by Django 4.2.2 on 2023-07-02 17:22

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
