# Generated by Django 4.2.2 on 2023-07-02 17:23

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Картинка отзыва',
                'verbose_name_plural': 'Картинки отзывов',
            },
        ),
    ]
