# Generated by Django 4.2.2 on 2023-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
        ('products', '0013_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_dislike',
            field=models.ManyToManyField(blank=True, related_name='profile_dislike_review', to='profile.profile', verbose_name='Пользователи, поставившие дизлайк'),
        ),
        migrations.AddField(
            model_name='review',
            name='profile_like',
            field=models.ManyToManyField(blank=True, related_name='profile_like_review', to='profile.profile', verbose_name='Пользователи, поставившие лайк'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True, verbose_name='Рейтинг'),
        ),
    ]
