# Generated by Django 4.2.2 on 2023-07-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_slug'),
        ('products', '0014_review_profile_dislike_review_profile_like_and_more'),
    ]

    operations = [
    ]
