# Generated by Django 4.2.2 on 2023-07-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_brand_country_brand_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название источника')),
                ('url', models.URLField(verbose_name='Ccылка на источник')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Ссылка на бренд',
                'verbose_name_plural': 'Ссылки на бренды',
            },
        ),
    ]
