# Generated by Django 4.2.2 on 2023-07-25 07:21

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_brandlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_images', to='products.series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Картинка серии',
                'verbose_name_plural': 'Картинки серий',
            },
        ),
    ]
