# Generated by Django 4.2.2 on 2023-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_name'),
        ('products', '0018_remove_product_category_remove_product_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_products', to='catalog.category', verbose_name='Категория'),
        ),
    ]
