# Generated by Django 4.2.2 on 2023-07-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_prescription_pricecategory_remove_product_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Ключевое действие',
                'verbose_name_plural': 'Ключевые действия',
            },
        ),
        migrations.CreateModel(
            name='KeyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Ключевый актив',
                'verbose_name_plural': 'Ключевые активы',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='use_description',
            field=models.TextField(blank=True, null=True, verbose_name='Применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_action',
            field=models.ManyToManyField(blank=True, related_name='key_action_products', to='products.keyaction', verbose_name='Ключевое действие'),
        ),
        migrations.AddField(
            model_name='product',
            name='key_asset',
            field=models.ManyToManyField(blank=True, related_name='key_asset_products', to='products.keyasset', verbose_name='Ключевой актив'),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.ManyToManyField(blank=True, related_name='key_asset_products', to='products.sex', verbose_name='Пол'),
        ),
    ]
