# Generated by Django 4.2.2 on 2023-07-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_keyaction_name_alter_keyaction_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Возрастная рекомендация',
                'verbose_name_plural': 'Возрастные рекомендации',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='age_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_recommendation_products', to='products.agerecommendation', verbose_name='Возрастные рекоммендации'),
        ),
    ]
