# Generated by Django 4.2.2 on 2023-07-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_category'),
        ('products', '0024_agerecommendation_product_age_recommendation'),
    ]

    operations = [
    ]
