# Generated by Django 4.2.2 on 2023-07-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_agerecommendation_product_age_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.ManyToManyField(blank=True, related_name='sex_products', to='products.sex', verbose_name='Пол'),
        ),
    ]
