# Generated by Django 4.2.2 on 2023-07-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_create_at_product_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
