# Generated by Django 4.2.2 on 2023-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_tag_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='brand_tags', to='products.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='series',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='series_tags', to='products.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='product_tags', to='products.tag', verbose_name='Теги'),
        ),
    ]
