# Generated by Django 4.2.2 on 2023-07-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка продукта', 'verbose_name_plural': 'Картинки продукта'},
        ),
    ]
