# Generated by Django 4.2.2 on 2023-08-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_sex'),
        ('products', '0027_series_slug'),
    ]

    operations = [
    ]
