# Generated by Django 4.2.2 on 2023-08-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_rename_create_at_product_created_at_and_more'),
        ('products', '0028_merge_0025_alter_product_sex_0027_series_slug'),
    ]

    operations = [
    ]
