# Generated by Django 4.2.2 on 2023-08-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productimage_options'),
        ('products', '0028_merge_0025_alter_product_sex_0027_series_slug'),
    ]

    operations = [
    ]
