# Generated by Django 4.2.2 on 2023-08-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_brand_tag_series_tag_alter_product_tag'),
        ('products', '0028_merge_0025_alter_product_sex_0027_series_slug'),
    ]

    operations = [
    ]
