# Generated by Django 4.2.2 on 2023-08-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_brand_tag_series_tag_alter_product_tag'),
        ('products', '0029_merge_20230801_1056'),
    ]

    operations = [
    ]
