# Generated by Django 4.2.2 on 2023-08-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_brand_tag_series_tag_alter_product_tag'),
        ('products', '0030_alter_product_created_at'),
    ]

    operations = [
    ]
