# Generated by Django 4.2.2 on 2023-08-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_merge_20230803_0803'),
        ('products', '0030_merge_20230803_0828'),
    ]

    operations = [
    ]
