# Generated by Django 4.2.2 on 2023-08-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_merge_20230803_0803'),
        ('products', '0029_merge_20230803_0805'),
        ('products', '0031_merge_20230803_1028'),
    ]

    operations = [
    ]
