# Generated by Django 4.2.2 on 2023-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_merge_20230803_0828'),
        ('products', '0032_alter_brand_manufacturer'),
    ]

    operations = [
    ]
