# Generated by Django 4.2.2 on 2023-08-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_merge_20230804_0742'),
        ('products', '0032_merge_20230804_1253'),
        ('products', '0033_merge_20230803_1244'),
    ]

    operations = [
    ]
