# Generated by Django 4.2.2 on 2023-08-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesimage',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seria_images', to='products.series', verbose_name='Серия'),
        ),
        migrations.CreateModel(
            name='SeriesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ccылка на баннер')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_banners', to='products.series', verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ccылка на баннер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_banners', to='products.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='BrandBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ccылка на баннер')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_banners', to='products.brand', verbose_name='Бренд')),
            ],
        ),
    ]
