# Generated by Django 4.2.2 on 2023-08-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
