# Generated by Django 4.2.2 on 2023-08-09 15:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_review_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание бренда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='use_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Применение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
