# Generated by Django 4.2.2 on 2023-08-08 16:15

import apps.tools.database_operations
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_alter_seriesimage_series_seriesbanner_productbanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(default=django.utils.timezone.now, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
