# Generated by Django 4.2.2 on 2023-08-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_brand_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='status_watermark',
            field=models.BooleanField(default=False, verbose_name='Необходим копирайт'),
        ),
    ]
