# Generated by Django 4.2.2 on 2023-08-09 08:00

import apps.tools.database_operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_brandbanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandbanner',
            name='image',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbanner',
            name='image',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriesbanner',
            name='image',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
