# Generated by Django 4.2.2 on 2023-08-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_brand_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile_dislike',
        ),
        migrations.RemoveField(
            model_name='review',
            name='profile_like',
        ),
    ]
