# Generated by Django 4.2.2 on 2023-08-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_brandbanner_image_productbanner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandbanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productbanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='seriesbanner',
            name='image',
        ),
    ]
