# Generated by Django 4.2.2 on 2023-08-09 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_remove_brandbanner_image_remove_productbanner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesbanner',
            name='brand',
        ),
        migrations.AddField(
            model_name='seriesbanner',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='series_banners', to='products.series', verbose_name='Cерия'),
            preserve_default=False,
        ),
    ]
