# Generated by Django 4.2.2 on 2023-08-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_review_is_publish'),
        ('products', '0041_remove_seriesbanner_brand_seriesbanner_series'),
    ]

    operations = [
    ]
