# Generated by Django 4.2.2 on 2023-08-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_alter_brand_name_alter_product_name_and_more'),
        ('products', '0042_merge_20230809_1115'),
    ]

    operations = [
    ]
