# Generated by Django 4.2.2 on 2023-08-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_merge_20230816_0831'),
        ('products', '0044_rename_date_review_created_at'),
    ]

    operations = [
    ]
