# Generated by Django 4.2.2 on 2023-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_productimage_status_watermark'),
        ('products', '0045_merge_20230816_1014'),
    ]

    operations = [
    ]
