# Generated by Django 4.2.2 on 2023-08-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_review_profile_dislike_and_more'),
        ('products', '0046_merge_20230821_0734'),
    ]

    operations = [
    ]
