# Generated by Django 4.2.2 on 2023-08-21 08:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_merge_20230821_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
