# Generated by Django 4.2.2 on 2023-08-21 09:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
    ]
