# Generated by Django 4.2.2 on 2023-08-24 14:26

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0025_alter_manufacturertariffhistory_tariff_plan'),
        ('products', '0049_review_updated_at_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_brands', to='manufacturers.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
        ),
    ]
