# Generated by Django 4.2.2 on 2023-08-31 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_brand_image_alter_brand_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandlink',
            options={'verbose_name': 'Ссылка магазины бренда', 'verbose_name_plural': 'Ссылки на бренды брендов'},
        ),
        migrations.AlterField(
            model_name='brandlink',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_links', to='products.brand', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название источника')),
                ('url', models.URLField(verbose_name='Ccылка на источник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ссылка магазины продукта',
                'verbose_name_plural': 'Ссылки на бренды продукта',
            },
        ),
    ]
