# Generated by Django 4.2.2 on 2023-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_brandlink_options_alter_brandlink_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlink',
            options={'verbose_name': 'Ссылка на магазины продукта', 'verbose_name_plural': 'Ссылки на магазины продуктов'},
        ),
        migrations.AlterField(
            model_name='brandlink',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='brandlink',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на источник'),
        ),
    ]
