# Generated by Django 4.2.2 on 2023-08-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_alter_productlink_options_alter_brandlink_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandlink',
            options={'verbose_name': 'Ссылка магазины бренда', 'verbose_name_plural': 'Ссылки на магазины брендов'},
        ),
    ]
