# Generated by Django 4.2.2 on 2023-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_alter_brandbanner_banner_alter_productbanner_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandbanner',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ccылка на баннер'),
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ccылка на баннер'),
        ),
        migrations.AlterField(
            model_name='seriesbanner',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ccылка на баннер'),
        ),
    ]
