# Generated by Django 4.2.2 on 2023-09-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_alter_brandbanner_url_alter_productbanner_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandlink',
            name='url',
        ),
        migrations.RemoveField(
            model_name='productlink',
            name='url',
        ),
    ]
