# Generated by Django 4.2.2 on 2023-09-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_remove_brandlink_url_remove_productlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandlink',
            name='url',
            field=models.URLField(default=1, max_length=500, verbose_name='Ccылка на источник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlink',
            name='url',
            field=models.URLField(default=1, max_length=500, verbose_name='Ccылка на источник'),
            preserve_default=False,
        ),
    ]
