# Generated by Django 4.2.2 on 2023-09-06 14:17

import apps.tools.database_operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_brandlink_url_productlink_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='logo',
            field=apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
        ),
    ]
