# Generated by Django 4.2.2 on 2023-09-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_blockcomment'),
        ('products', '0064_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='block_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.blockcomment', verbose_name='Причина блокировки'),
        ),
    ]
