# Generated by Django 4.2.2 on 2023-10-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_socialweb'),
        ('products', '0065_review_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_social_links', to='products.brand', verbose_name='Бренд')),
                ('social_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_social_links', to='settings.socialweb', verbose_name='Социальная сеть')),
            ],
        ),
    ]
