# Generated by Django 4.2.2 on 2023-10-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_socialweb'),
        ('products', '0066_brandsociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsociallink',
            name='social_web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='settings.socialweb', verbose_name='Социальная сеть'),
        ),
    ]
