# Generated by Django 4.2.2 on 2023-10-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_alter_brandsociallink_social_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandsociallink',
            name='social_web',
        ),
    ]
