# Generated by Django 4.2.2 on 2023-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_brandsociallink_social_web_brandsociallink_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandsociallink',
            options={'verbose_name': 'Ссылка на социальную сеть', 'verbose_name_plural': 'Ссылки на социальные сети'},
        ),
    ]
