# Generated by Django 4.2.2 on 2023-10-09 11:20

import apps.tools.database_operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_format_product_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seriesbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(default=1, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
