# Generated by Django 4.2.2 on 2023-10-10 09:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_alter_brandbanner_banner_alter_productbanner_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Короткое писание бренда'),
        ),
    ]
