# Generated by Django 4.2.2 on 2023-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_brand_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_status',
            field=models.BooleanField(default=True, verbose_name='Новое средство'),
        ),
    ]
