# Generated by Django 4.2.2 on 2023-10-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
