# Generated by Django 4.2.2 on 2023-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0079_remove_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
