# Generated by Django 4.2.2 on 2023-10-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0074_overviewcomment_block_type'),
        ('products', '0080_series_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.PositiveIntegerField(choices=[(0, 'Удаление'), (1, 'Добавление')], default=1, verbose_name='Тип действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_subscribers', to='products.brand', verbose_name='Бренд')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_brands', to='profile.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'История подписки на бренд',
                'verbose_name_plural': 'История подписок на бренд',
            },
        ),
    ]
