# Generated by Django 4.2.2 on 2023-07-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='period',
            field=models.PositiveIntegerField(choices=[(3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], max_length=20, verbose_name='Период'),
        ),
    ]
