# Generated by Django 4.2.2 on 2023-07-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_tariff_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Цена тарифа'),
        ),
    ]
