# Generated by Django 4.2.2 on 2023-07-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_tariff_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='period',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='quantity',
        ),
    ]
