# Generated by Django 4.2.2 on 2023-07-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_tariff_period_remove_tariff_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField(verbose_name='Период/месяцы')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество средств в каталоге')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.plan', verbose_name='Тарифный план'),
        ),
    ]
