# Generated by Django 4.2.2 on 2023-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_plan_tariff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.PositiveIntegerField(verbose_name='Период действия'),
        ),
    ]
