# Generated by Django 4.2.2 on 2023-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_additionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
