# Generated by Django 4.2.2 on 2023-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_additionalservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.PositiveIntegerField(verbose_name='Период действия/месяц'),
        ),
    ]
