# Generated by Django 4.2.2 on 2023-08-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_plan_status_start_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Цена тарифа'),
            preserve_default=False,
        ),
    ]
