# Generated by Django 4.2.2 on 2023-08-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_tariff_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.plan', verbose_name='Тарифный план'),
            preserve_default=False,
        ),
    ]
