# Generated by Django 4.2.2 on 2023-07-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_cooperation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Cooperation',
        ),
    ]
