# Generated by Django 4.2.2 on 2023-07-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='type',
        ),
        migrations.DeleteModel(
            name='TypePage',
        ),
    ]
