# Generated by Django 4.2.2 on 2023-08-09 15:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_remove_mainpage_type_delete_typepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Содержимое страницы'),
        ),
    ]
