# Generated by Django 4.2.2 on 2023-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_mainbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='banner_selection',
            field=models.BooleanField(default=False, verbose_name='Баннер для блока подбора косметики'),
        ),
    ]
