# Generated by Django 4.2.2 on 2023-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='link_shop',
            field=models.ManyToManyField(blank=True, related_name='link_shop_manufacturers', to='manufacturers.linkshop'),
        ),
    ]
