# Generated by Django 4.2.2 on 2023-07-14 10:10

import apps.tools.database_operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0004_manufacturer_banner_manufacturer_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Проищводитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='link_banner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Логотип компании'),
        ),
    ]
