# Generated by Django 4.2.2 on 2023-07-18 09:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0005_alter_manufacturer_options_manufacturer_link_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkshop',
            options={'verbose_name': 'Интернет магазин', 'verbose_name_plural': 'Интернет магазины'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='linkshop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='linkshop',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на магазин'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание компании'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='history',
            field=models.TextField(blank=True, verbose_name='История компании'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='link_banner',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка к баннеру'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='link_shop',
            field=models.ManyToManyField(blank=True, related_name='link_shop_manufacturers', to='manufacturers.linkshop', verbose_name='Ссылка на магазины'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='principle',
            field=models.TextField(blank=True, verbose_name='Принципы компании'),
        ),
    ]
