# Generated by Django 4.2.2 on 2023-07-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0006_alter_linkshop_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='user',
        ),
    ]
