# Generated by Django 4.2.2 on 2023-07-18 14:39

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_answer_product_alter_answer_question_and_more'),
        ('manufacturers', '0006_alter_linkshop_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст рассылки')),
                ('image', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Изображение')),
                ('banner', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер')),
                ('background_image', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Фон')),
                ('link_banner', models.URLField(blank=True, null=True, verbose_name='Ссылка к баннеру')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_mails', to='manufacturers.manufacturer', verbose_name='Производитель')),
                ('receiver_profile', models.ManyToManyField(blank=True, related_name='profile_mails', to='profile.profile', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
