# Generated by Django 4.2.2 on 2023-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0007_manufacturer_tariff_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='start_day_tariff',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала действия тарифа'),
        ),
    ]
