# Generated by Django 4.2.2 on 2023-07-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0007_manufacturermailing'),
        ('manufacturers', '0008_manufacturer_profile'),
    ]

    operations = [
    ]
