# Generated by Django 4.2.2 on 2023-07-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0008_manufacturer_start_day_tariff'),
        ('manufacturers', '0009_merge_20230721_1543'),
    ]

    operations = [
    ]
