# Generated by Django 4.2.2 on 2023-07-25 10:26

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('manufacturers', '0010_merge_20230724_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkShop',
            new_name='ManufacturerLinkShop',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='link_shop',
        ),
    ]
