# Generated by Django 4.2.2 on 2023-07-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0013_alter_manufacturerlinkshop_manufacturer'),
    ]

    operations = [
    ]
