# Generated by Django 4.2.2 on 2023-08-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0015_merge_0014_manufacturer_tag_0014_merge_20230725_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='banner',
        ),
    ]
