# Generated by Django 4.2.2 on 2023-08-09 15:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0016_alter_manufacturer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturermailing',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст рассылки'),
        ),
    ]
