# Generated by Django 4.2.2 on 2023-08-09 09:36

import apps.products.mixins
import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0016_remove_manufacturer_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер')),
                ('url', models.URLField(verbose_name='Ccылка на баннер')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_banners', to='manufacturers.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'abstract': False,
            },
            bases=(models.Model, apps.products.mixins.ViewMixin),
        ),
    ]
