# Generated by Django 4.2.2 on 2023-08-18 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_review_profile_dislike_and_more'),
        ('manufacturers', '0017_alter_manufacturermailing_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_reviews_answers', to='manufacturers.manufacturer', verbose_name='Производитель')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_answers', to='products.review', verbose_name='Отызыв')),
            ],
            options={
                'verbose_name': 'Ответ производителя на отзыв',
                'verbose_name_plural': 'Ответы производителей на отзывы',
            },
        ),
    ]
