# Generated by Django 4.2.2 on 2023-08-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0017_alter_manufacturermailing_text'),
        ('manufacturers', '0017_manufacturerbanner'),
    ]

    operations = [
    ]
