# Generated by Django 4.2.2 on 2023-08-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0018_merge_20230814_0900'),
        ('manufacturers', '0018_merge_20230816_0831'),
    ]

    operations = [
    ]
