# Generated by Django 4.2.2 on 2023-08-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0018_answerreview'),
        ('manufacturers', '0019_merge_20230816_1014'),
    ]

    operations = [
    ]
