# Generated by Django 4.2.2 on 2023-08-21 09:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0020_merge_0018_answerreview_0019_merge_20230816_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerreview',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='answerreview',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='answerreview',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='answerreview',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
