# Generated by Django 4.2.2 on 2023-08-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0022_remove_manufacturer_start_day_tariff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='link_banner',
        ),
    ]
