# Generated by Django 4.2.2 on 2023-08-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_plan_status_start_plan'),
        ('manufacturers', '0024_manufacturertariffhistory_manufacturerservicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturertariffhistory',
            name='tariff_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_manufacturers', to='services.tariff', verbose_name='Тарифный план'),
        ),
    ]
