# Generated by Django 4.2.2 on 2023-08-24 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0024_manufacturertariffhistory_manufacturerservicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturermailing',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата рассылки'),
            preserve_default=False,
        ),
    ]
