# Generated by Django 4.2.2 on 2023-08-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0025_alter_manufacturertariffhistory_tariff_plan'),
        ('manufacturers', '0025_manufacturermailing_created_at'),
    ]

    operations = [
    ]
