# Generated by Django 4.2.2 on 2023-08-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_brand_image_alter_brand_manufacturer_and_more'),
        ('manufacturers', '0026_merge_20230825_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_review_answer', to='manufacturers.manufacturer', verbose_name='Профиль отвечающего')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_answer', to='products.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ производителя на отзыв',
                'verbose_name_plural': 'Ответы производителей на отзывы',
            },
        ),
    ]
