# Generated by Django 4.2.2 on 2023-08-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_brand_image_alter_brand_manufacturer_and_more'),
        ('profile', '0059_delete_answer'),
        ('manufacturers', '0028_rename_profile_manufacturerreviewanswer_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_answers', to='manufacturers.manufacturer', verbose_name='Профиль отвечающего')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='profile.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ производителя на вопрос',
                'verbose_name_plural': 'Ответы производителей на вопросы',
            },
        ),
    ]
