# Generated by Django 4.2.2 on 2023-08-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0029_manufacturerquestionanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerlinkshop',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_links', to='manufacturers.manufacturer', verbose_name='Производитель'),
        ),
    ]
