# Generated by Django 4.2.2 on 2023-08-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0030_alter_manufacturerlinkshop_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerlinkshop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='manufacturerlinkshop',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Ссылка на источник'),
        ),
    ]
