# Generated by Django 4.2.2 on 2023-09-18 11:35

import apps.tools.database_operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0032_alter_manufacturerlinkshop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerbanner',
            name='banner',
            field=apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='manufacturerbanner',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ccылка на баннер'),
        ),
        migrations.AlterField(
            model_name='manufacturerlinkshop',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ccылка на источник'),
        ),
    ]
