# Generated by Django 4.2.2 on 2023-10-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_socialweb'),
        ('manufacturers', '0034_answerreview_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_social_links', to='manufacturers.manufacturer', verbose_name='Производитель')),
                ('social_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.socialweb', verbose_name='Социальная сеть')),
            ],
        ),
    ]
