# Generated by Django 4.2.2 on 2023-10-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0035_manufacturersociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturersociallink',
            name='social_web',
        ),
    ]
