# Generated by Django 4.2.2 on 2023-10-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0037_manufacturersociallink_social_web_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturersociallink',
            options={'verbose_name': 'Ссылка на социальную сеть', 'verbose_name_plural': 'Ссылки на социальные сети'},
        ),
    ]
