# Generated by Django 4.2.2 on 2023-10-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0039_alter_manufacturerbanner_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManufacturerReviewAnswer',
        ),
    ]
