# Generated by Django 4.2.2 on 2023-10-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0040_delete_manufacturerreviewanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerquestionanswer',
            name='product',
        ),
    ]
