# Generated by Django 4.2.2 on 2023-07-02 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_password_reset_links', to='profile.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
