# Generated by Django 4.2.2 on 2023-06-30 16:29

import apps.tools.database_operations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20230628_1602'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(blank=True, max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('avatar', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
                ('sex', models.PositiveIntegerField(blank=True, choices=[(0, 'M'), (1, 'F')], null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('hair_type', models.CharField(blank=True, max_length=50)),
                ('skin_type', models.CharField(blank=True, max_length=50)),
                ('accept_news', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='settings.country', verbose_name='Страна')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
