# Generated by Django 4.2.2 on 2023-07-12 09:07

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('subject_appeal', models.PositiveIntegerField(blank=True, choices=[(0, 'Техническая поддержка'), (1, 'Общие вопросы и предложения'), (2, 'Юридические и финансовые вопросы')], default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_appeals', to='profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AppealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profile.appeal', verbose_name='Обращение')),
            ],
        ),
    ]
