# Generated by Django 4.2.2 on 2023-07-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_reviewimage'),
        ('profile', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата вопроса')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to='products.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_questions', to='profile.profile')),
            ],
        ),
    ]
