# Generated by Django 4.2.2 on 2023-07-17 16:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_appeal_appealimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='appealimage',
            options={'verbose_name': 'Фото обращения', 'verbose_name_plural': 'Фото обращения'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_appeals', to='profile.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='subject_appeal',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Техническая поддержка'), (1, 'Общие вопросы и предложения'), (2, 'Юридические и финансовые вопросы')], default=0, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.TextField(verbose_name='Текст обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Заголовок обращения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accept_news',
            field=models.BooleanField(default=False, verbose_name='Принимать новости'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип волос'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, verbose_name='Ник'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Публичный email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'M'), (1, 'F')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skin_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип кожи'),
        ),
    ]
