# Generated by Django 4.2.2 on 2023-07-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_appeal_options_alter_appealimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Активен'),
        ),
    ]
