# Generated by Django 4.2.2 on 2023-07-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_question_options_answer'),
        ('profile', '0005_alter_profile_is_active'),
    ]

    operations = [
    ]
