# Generated by Django 4.2.2 on 2023-07-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_alter_profile_is_active'),
        ('profile', '0007_alter_answer_product_alter_answer_question_and_more'),
    ]

    operations = [
    ]
