# Generated by Django 4.2.2 on 2023-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_merge_20230718_0909'),
        ('profile', '0007_alter_answer_product_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_brands',
            field=models.ManyToManyField(blank=True, related_name='profile_brand_favorite', to='products.brand', verbose_name='Список избранных брендов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='profile_product_favorite', to='products.product', verbose_name='Список избранных средств'),
        ),
    ]
