# Generated by Django 4.2.2 on 2023-07-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_merge_20230721_1543'),
        ('profile', '0008_profile_favorite_brands_profile_favorite_products'),
    ]

    operations = [
    ]
