# Generated by Django 4.2.2 on 2023-07-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_merge_20230724_0832'),
        ('profile', '0008_merge_20230724_1455'),
        ('profile', '0009_merge_20230721_1753'),
    ]

    operations = [
    ]
