# Generated by Django 4.2.2 on 2023-07-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_merge_20230725_1341'),
    ]

    operations = [
    ]
