# Generated by Django 4.2.2 on 2023-07-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articleanswercomment_profile'),
        ('profile', '0010_merge_20230725_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='profile_article_favorite', to='blog.article', verbose_name='Список избранных статей'),
        ),
    ]
