# Generated by Django 4.2.2 on 2023-07-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0013_alter_manufacturerlinkshop_manufacturer'),
        ('profile', '0011_profile_favorite_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_answers', to='manufacturers.manufacturer'),
        ),
    ]
