# Generated by Django 4.2.2 on 2023-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_views'),
        ('profile', '0012_answer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_products',
            field=models.ManyToManyField(blank=True, related_name='profiles_likes_product', to='products.product', verbose_name='Понравившиеся продукты'),
        ),
    ]
