# Generated by Django 4.2.2 on 2023-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_alter_authorhistory_close_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorhistory',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания действия статуса'),
        ),
    ]
