# Generated by Django 4.2.2 on 2023-07-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_profile_like_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_articles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_brands',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_products',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='like_products',
        ),
    ]
