# Generated by Django 4.2.2 on 2023-07-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile', '0015_likeaction_favoriteaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteaction',
            options={'verbose_name': 'История добавления в избранное', 'verbose_name_plural': 'История добавлений в избранное'},
        ),
        migrations.AlterModelOptions(
            name='likeaction',
            options={'verbose_name': 'История лайков', 'verbose_name_plural': 'История лайков'},
        ),
        migrations.AlterField(
            model_name='favoriteaction',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='favoriteaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='likeaction',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='likeaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
