# Generated by Django 4.2.2 on 2023-07-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_alter_author_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorhistory',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Заблокирован на время', 'Заблокирован на время'), ('Заблокирован навсегда', 'Заблокирован навсегда')], default='Активен', max_length=55, verbose_name='Статус пользователя'),
        ),
    ]
