# Generated by Django 4.2.2 on 2023-07-28 14:33

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_alter_authorhistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок обзора')),
                ('description', models.TextField(verbose_name='Текст статьи')),
                ('thumbnail', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Главная фотография')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='profile.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='OverviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Главная фотография')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_overview', to='profile.overview', verbose_name='Обзор')),
            ],
            options={
                'verbose_name': 'Фотография обзора',
                'verbose_name_plural': 'Фотографии обзоров',
            },
        ),
    ]
