# Generated by Django 4.2.2 on 2023-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_alter_favoriteaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteaction',
            name='type_action',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Удаление'), (1, 'Добавление')], null=True, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='likeaction',
            name='type_action',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Удаление'), (1, 'Добавление')], null=True, verbose_name='Тип действия'),
        ),
    ]
