# Generated by Django 4.2.2 on 2023-08-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_merge_20230725_1349'),
        ('profile', '0017_alter_favoriteaction_type_action_and_more'),
    ]

    operations = [
    ]
