# Generated by Django 4.2.2 on 2023-07-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_alter_overview_options_overview_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='count_gratitude',
            field=models.PositiveIntegerField(default=0, verbose_name='Число благодарностей'),
        ),
    ]
