# Generated by Django 4.2.2 on 2023-07-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_author_count_gratitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='overview',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='OverviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='profile.author', verbose_name='Автор комментария')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_comments', to='profile.overview', verbose_name='Обзор')),
            ],
            options={
                'verbose_name': 'Комментарий обзора',
                'verbose_name_plural': 'Комментарии обзоров',
            },
        ),
    ]
