# Generated by Django 4.2.2 on 2023-08-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_merge_20230725_1349'),
        ('profile', '0020_overview_created_at_overview_is_draft_and_more'),
    ]

    operations = [
    ]
