# Generated by Django 4.2.2 on 2023-08-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0021_merge_20230801_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='current_status',
            field=models.CharField(choices=[('Active', 'Активен'), ('Blocked until', 'Заблокирован на время'), ('Blocked forever', 'Заблокирован навсегда')], default='Active', max_length=55, verbose_name='Текущий статус активности'),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Читатель'), (1, 'Автор')], default=0, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='authorhistory',
            name='status',
            field=models.CharField(choices=[('Active', 'Активен'), ('Blocked until', 'Заблокирован на время'), ('Blocked forever', 'Заблокирован навсегда')], default='Активен', max_length=55, verbose_name='Статус пользователя'),
        ),
    ]
