# Generated by Django 4.2.2 on 2023-08-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_merge_20230801_1056'),
        ('profile', '0023_alter_overviewcomment_created_at'),
    ]

    operations = [
    ]
