# Generated by Django 4.2.2 on 2023-08-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0024_merge_20230803_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
