# Generated by Django 4.2.2 on 2023-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0025_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='subject_appeal',
            field=models.CharField(choices=[('TS', 'Техническая поддержка'), ('QS', 'Общие вопросы и предложения'), ('LF', 'Юридические и финансовые вопросы')], default='TS', max_length=2, verbose_name='Тема обращения'),
        ),
    ]
