# Generated by Django 4.2.2 on 2023-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0026_alter_appeal_subject_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='subject_appeal',
            field=models.CharField(choices=[('TS', 'Техническая поддержка'), ('QS', 'Общие вопросы и предложения'), ('LF', 'Юридические и финансовые вопросы')], default='TS', max_length=25, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='current_status',
            field=models.CharField(choices=[('AT', 'Активен'), ('BU', 'Заблокирован на время'), ('BF', 'Заблокирован навсегда')], default='AT', max_length=25, verbose_name='Текущий статус активности'),
        ),
    ]
