# Generated by Django 4.2.2 on 2023-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_alter_author_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='authorhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='authorhistory',
            name='current_status',
            field=models.CharField(choices=[('AT', 'Активен'), ('BU', 'Заблокирован на время'), ('BF', 'Заблокирован навсегда')], default='AT', max_length=25, verbose_name='Текущий статус активности'),
        ),
    ]
