# Generated by Django 4.2.2 on 2023-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0029_remove_author_current_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteaction',
            name='type_action',
            field=models.PositiveIntegerField(choices=[(0, 'Удаление'), (1, 'Добавление')], default=1, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='likeaction',
            name='type_action',
            field=models.PositiveIntegerField(choices=[(0, 'Удаление'), (1, 'Добавление')], default=1, verbose_name='Тип действия'),
        ),
    ]
