# Generated by Django 4.2.2 on 2023-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0034_conversion_delete_followingpageaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='profile_subscribers', to='profile.profile', verbose_name='Подписчики'),
        ),
    ]
