# Generated by Django 4.2.2 on 2023-08-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0035_author_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='count_gratitude',
        ),
        migrations.AddField(
            model_name='author',
            name='gratitude',
            field=models.ManyToManyField(blank=True, related_name='profile_gratitude', to='profile.profile', verbose_name='Благодарности'),
        ),
    ]
