# Generated by Django 4.2.2 on 2023-08-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_additionalservice'),
        ('profile', '0037_rename_subscribers_author_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.additionalservice', verbose_name='Дополнительные услуги'),
        ),
    ]
