# Generated by Django 4.2.2 on 2023-08-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0035_bannerview'),
        ('profile', '0037_rename_subscribers_author_subscriber'),
    ]

    operations = [
    ]
