# Generated by Django 4.2.2 on 2023-08-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorhistory',
            name='close_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия статуса'),
        ),
        migrations.AlterField(
            model_name='authorhistory',
            name='created_at',
            field=models.DateField(verbose_name='Дата начала действия статуса'),
        ),
    ]
