# Generated by Django 4.2.2 on 2023-08-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overviewcomment',
            name='overview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profile.overview', verbose_name='Обзор'),
        ),
    ]
