# Generated by Django 4.2.2 on 2023-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewphoto',
            name='status_watermark',
            field=models.BooleanField(default=False, verbose_name='Необходим копирайт'),
        ),
    ]
