# Generated by Django 4.2.2 on 2023-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_alter_overviewcomment_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='total_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий рейтинг'),
        ),
    ]
