# Generated by Django 4.2.2 on 2023-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_merge_20230809_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
