# Generated by Django 4.2.2 on 2023-08-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_merge_20230809_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='gratitude',
        ),
        migrations.RemoveField(
            model_name='author',
            name='subscriber',
        ),
    ]
