# Generated by Django 4.2.2 on 2023-08-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_alter_authorhistory_close_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorhistory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание статуса'),
        ),
    ]
