# Generated by Django 4.2.2 on 2023-08-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_profile_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
