# Generated by Django 4.2.2 on 2023-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0039_overview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сессия пользователя'),
        ),
    ]
