# Generated by Django 4.2.2 on 2023-08-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0040_profileservicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileservicehistory',
            name='start_date',
            field=models.DateField(),
        ),
    ]
