# Generated by Django 4.2.2 on 2023-08-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0040_subscribreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribreaction',
            name='profile_subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_signed', to='profile.profile', verbose_name='Профиль подписчика'),
        ),
        migrations.CreateModel(
            name='GratitudeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.PositiveIntegerField(choices=[(0, 'Удаление'), (1, 'Добавление')], default=1, verbose_name='Тип действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_gratitudes', to='profile.profile', verbose_name='Профиль автора')),
                ('profile_gratitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles_gratitude', to='profile.profile', verbose_name='Профиль благодаришего')),
            ],
            options={
                'verbose_name': 'История благодарности',
                'verbose_name_plural': 'История благодарностей',
            },
        ),
    ]
