# Generated by Django 4.2.2 on 2023-08-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0041_alter_subscribreaction_profile_subscribe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribreAction',
        ),
    ]
