# Generated by Django 4.2.2 on 2023-08-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0042_delete_subscribreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribreAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.PositiveIntegerField(choices=[(0, 'Удаление'), (1, 'Добавление')], default=1, verbose_name='Тип действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_subscribers', to='profile.author', verbose_name='Профиль автора')),
                ('author_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_signed', to='profile.author', verbose_name='Профиль подписчика')),
            ],
            options={
                'verbose_name': 'История подписки',
                'verbose_name_plural': 'История подписок',
            },
        ),
    ]
