# Generated by Django 4.2.2 on 2023-08-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0043_subscribreaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GratitudeAction',
        ),
    ]
