# Generated by Django 4.2.2 on 2023-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0045_gratitudeaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribreAction',
            new_name='SubscribeAction',
        ),
    ]
