# Generated by Django 4.2.2 on 2023-08-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0039_overview_slug'),
        ('profile', '0046_rename_subscribreaction_subscribeaction'),
    ]

    operations = [
    ]
