# Generated by Django 4.2.2 on 2023-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_overviewcomment_parent'),
        ('profile', '0038_overviewphoto_status_watermark'),
        ('profile', '0039_authorhistory_description'),
        ('profile', '0039_overview_total_rating'),
        ('profile', '0040_viewaction_session_id'),
        ('profile', '0043_alter_profile_is_active'),
        ('profile', '0047_merge_20230816_1014'),
    ]

    operations = [
    ]
