# Generated by Django 4.2.2 on 2023-08-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0050_alter_overviewcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overviewcomment',
            options={'verbose_name': 'Комментарий обзора', 'verbose_name_plural': 'Комментарии обзоров'},
        ),
    ]
