# Generated by Django 4.2.2 on 2023-08-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_additionalservice_price'),
        ('profile', '0052_alter_bannerview_type_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileservicehistory',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание действия'),
        ),
        migrations.AlterField(
            model_name='profileservicehistory',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Начало действия'),
        ),
        migrations.CreateModel(
            name='ProfileTariffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание действия')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tariffs', to='profile.profile', verbose_name='Профиль')),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tariff_profiles', to='services.tariff', verbose_name='Тарифный план')),
            ],
        ),
    ]
