# Generated by Django 4.2.2 on 2023-08-24 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0054_remove_profiletariffhistory_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='bannerview',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_banners_views', to='profile.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='conversions_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_conversions', to='profile.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.PositiveIntegerField(blank=True, choices=[('0', 'M'), ('1', 'F')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='viewaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_actions', to='profile.profile', verbose_name='Профиль'),
        ),
    ]
