# Generated by Django 4.2.2 on 2023-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0055_alter_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
