# Generated by Django 4.2.2 on 2023-08-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0025_manufacturermailing_created_at'),
        ('profile', '0056_alter_overview_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_answers', to='manufacturers.manufacturer', verbose_name='Профиль отвечающего'),
            preserve_default=False,
        ),
    ]
