# Generated by Django 4.2.2 on 2023-08-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0055_ip_created_at_profile_created_at_profile_updated_at_and_more'),
        ('profile', '0057_alter_answer_profile'),
    ]

    operations = [
    ]
