# Generated by Django 4.2.2 on 2023-08-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0058_merge_20230825_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
