# Generated by Django 4.2.2 on 2023-08-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0059_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerview',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_views_banners', to='profile.ip', verbose_name='IP-aдрес'),
        ),
        migrations.AlterField(
            model_name='viewaction',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_views', to='profile.ip', verbose_name='IP-aдрес'),
        ),
    ]
