# Generated by Django 4.2.2 on 2023-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0060_alter_bannerview_ip_alter_viewaction_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
