# Generated by Django 4.2.2 on 2023-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0063_alter_bannerview_ip_alter_viewaction_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerview',
            name='session_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Сессия пользователя'),
        ),
    ]
