# Generated by Django 4.2.2 on 2023-08-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0065_delete_bannerview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_author', to='profile.profile', verbose_name='Профиль'),
        ),
    ]
