# Generated by Django 4.2.2 on 2023-08-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0066_alter_author_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gratitudeaction',
            old_name='author_gratitude',
            new_name='author_action',
        ),
        migrations.RenameField(
            model_name='subscribeaction',
            old_name='author_subscriber',
            new_name='author_action',
        ),
    ]
