# Generated by Django 4.2.2 on 2023-09-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0068_linkaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkAction',
        ),
    ]
