# Generated by Django 4.2.2 on 2023-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_agerecommendation_slug_alter_keyaction_slug_and_more'),
        ('profile', '0069_delete_linkaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='overview_tags', to='products.tag', verbose_name='Теги'),
        ),
    ]
