# Generated by Django 4.2.2 on 2023-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0071_overview_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewcomment',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
