# Generated by Django 4.2.2 on 2023-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0072_overviewcomment_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
