# Generated by Django 4.2.2 on 2023-12-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0075_alter_profile_contact_email_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[('R', 'Читатель'), ('A', 'Автор'), ('M', 'Производитель')], default='R', max_length=25, verbose_name='Тип пользователя'),
        ),
    ]
