# Generated by Django 4.2.2 on 2023-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
