# Generated by Django 4.2.2 on 2023-07-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
        ('blog', '0005_article_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.articlecomment', verbose_name='Комментарий')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_article_answers', to='profile.profile', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий статьи',
                'verbose_name_plural': 'Ответы на комментарии статей',
            },
        ),
    ]
