# Generated by Django 4.2.2 on 2023-07-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_reviewimage'),
        ('blog', '0005_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_articles', to='products.brand', verbose_name='Бренд'),
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='blog.article', verbose_name='Ссылка на продукт')),
            ],
            options={
                'verbose_name': 'Ссылка на продукт',
                'verbose_name_plural': 'Ссылки на продукты',
            },
        ),
    ]
