# Generated by Django 4.2.2 on 2023-07-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
        ('blog', '0005_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile_like',
            field=models.ManyToManyField(related_name='profile_like_articles', to='profile.profile'),
        ),
    ]
