# Generated by Django 4.2.2 on 2023-07-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_brand_articlelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelink',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
