# Generated by Django 4.2.2 on 2023-07-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
        ('blog', '0009_remove_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile_view',
            field=models.ManyToManyField(blank=True, related_name='profile_view_articles', to='profile.profile'),
        ),
    ]
