# Generated by Django 4.2.2 on 2023-07-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_slug'),
        ('blog', '0006_articleanswercomment'),
        ('blog', '0006_articlecomment_likes'),
        ('blog', '0007_alter_articlelink_url'),
        ('blog', '0011_article_views'),
    ]

    operations = [
    ]
