# Generated by Django 4.2.2 on 2023-07-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_merge_20230718_0909'),
        ('blog', '0012_merge_20230718_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleanswercomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_article_answers', to='profile.profile', verbose_name='Профиль'),
        ),
    ]
