# Generated by Django 4.2.2 on 2023-07-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_merge_20230725_1341'),
        ('blog', '0013_alter_articleanswercomment_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Тема жалобы')),
                ('text', models.TextField(verbose_name='Описание причины')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='blog.article', verbose_name='Статья')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_complaints', to='profile.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
