# Generated by Django 4.2.2 on 2023-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articleanswercomment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
