# Generated by Django 4.2.2 on 2023-08-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='articlecomment',
            old_name='date',
            new_name='created_at',
        ),
    ]
