# Generated by Django 4.2.2 on 2023-08-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0014_merge_20230725_1348'),
        ('blog', '0014_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_articles', to='manufacturers.manufacturer', verbose_name='Производитель'),
        ),
    ]
