# Generated by Django 4.2.2 on 2023-08-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0014_merge_20230725_1348'),
        ('blog', '0015_article_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_articles', to='manufacturers.manufacturer', verbose_name='Производитель'),
        ),
    ]
