# Generated by Django 4.2.2 on 2023-08-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_articlecomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
