# Generated by Django 4.2.2 on 2023-08-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_complaint'),
        ('blog', '0015_article_is_active'),
    ]

    operations = [
    ]
