# Generated by Django 4.2.2 on 2023-08-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_merge_20230725_1349'),
        ('blog', '0016_merge_0014_complaint_0015_article_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_articles', to='profile.profile', verbose_name='Профиль'),
        ),
    ]
