# Generated by Django 4.2.2 on 2023-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_manufacturer'),
        ('blog', '0016_alter_articlecomment_created_at'),
    ]

    operations = [
    ]
