# Generated by Django 4.2.2 on 2023-08-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_articlecomment_created_at'),
        ('blog', '0017_article_profile'),
    ]

    operations = [
    ]
