# Generated by Django 4.2.2 on 2023-08-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_merge_20230803_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile',
        ),
    ]
