# Generated by Django 4.2.2 on 2023-08-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_merge_20230803_1244'),
        ('blog', '0019_remove_article_profile'),
    ]

    operations = [
    ]
