# Generated by Django 4.2.2 on 2023-08-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_remove_product_views'),
        ('blog', '0021_remove_article_likes_remove_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='articles_tags', to='products.tag', verbose_name='Теги'),
        ),
    ]
