# Generated by Django 4.2.2 on 2023-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlephoto',
            name='status_watermark',
            field=models.BooleanField(default=False, verbose_name='Необходим копирайт'),
        ),
    ]
