# Generated by Django 4.2.2 on 2023-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Общий рейтинг'),
        ),
    ]
