# Generated by Django 4.2.2 on 2023-08-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_articlecomment_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAnswerComment',
        ),
    ]
