# Generated by Django 4.2.2 on 2023-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_article_slug'),
        ('blog', '0023_article_total_rating'),
        ('blog', '0023_articlephoto_status_watermark'),
    ]

    operations = [
    ]
