# Generated by Django 4.2.2 on 2023-08-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
        ('blog', '0024_delete_articleanswercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.articlecomment', verbose_name='Корневой комментарий'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_articles_comments', to='profile.profile', verbose_name='Автор комментария'),
            preserve_default=False,
        ),
    ]
