# Generated by Django 4.2.2 on 2023-08-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_merge_20230821_0734'),
        ('blog', '0025_articlecomment_parent_articlecomment_profile'),
    ]

    operations = [
    ]
