# Generated by Django 4.2.2 on 2023-08-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_articlecomment_is_publish_articlecomment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='is_publish',
        ),
    ]
