# Generated by Django 4.2.2 on 2023-08-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_articlecomment_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile_like',
        ),
        migrations.RemoveField(
            model_name='article',
            name='profile_view',
        ),
    ]
