# Generated by Django 4.2.2 on 2023-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_article_profile_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликована'),
        ),
    ]
