# Generated by Django 4.2.2 on 2023-09-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_article_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
