# Generated by Django 4.2.2 on 2023-11-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile', '0075_alter_profile_contact_email_alter_profile_email_and_more'),
        ('blog', '0034_articlecomment_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='article',
        ),
        migrations.AddField(
            model_name='complaint',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_complaints_actions', to='profile.profile', verbose_name='Профиль'),
        ),
    ]
