# Generated by Django 4.2.2 on 2023-12-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0075_alter_profile_contact_email_alter_profile_email_and_more'),
        ('blog', '0035_remove_complaint_article_complaint_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='profile',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_articles_comments', to='profile.author', verbose_name='Автор комментария'),
        ),
    ]
