# Generated by Django 4.2.2 on 2023-07-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='profile_chats', to='profile.profile', verbose_name='Участники чата')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat')),
                ('profile_get', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_get_messages', to='profile.profile')),
                ('profile_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sent_messages', to='profile.profile')),
            ],
        ),
    ]
