# Generated by Django 4.2.2 on 2023-07-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile_get',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_messages', to='profile.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to='profile.profile'),
        ),
    ]
