# Generated by Django 4.2.2 on 2023-08-11 08:05

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
        ('chats', '0003_conversationpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_comments', to='chats.conversationpost', verbose_name='Пост')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_conversations_comments', to='profile.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Комметарий',
                'verbose_name_plural': 'Комметарии',
            },
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Фотография')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_conversation_images', to='chats.commentconversation', verbose_name='Комметрарий')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_conversation_answers', to='chats.commentconversation', verbose_name='Ответ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_conversations_answers', to='profile.profile', verbose_name='Профиль')),
            ],
        ),
    ]
