# Generated by Django 4.2.2 on 2023-08-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_commentconversation_imagecomment_answercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='commentconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
    ]
