# Generated by Django 4.2.2 on 2023-08-11 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
        ('chats', '0005_alter_commentconversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationpost',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='conversationpost',
            name='is_publish',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='conversationpost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_conversation_posts', to='profile.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='conversationpost',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
    ]
