# Generated by Django 4.2.2 on 2023-08-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_conversationpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercomment',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы на комментрарии'},
        ),
    ]
