# Generated by Django 4.2.2 on 2023-08-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_rename_subscribers_author_subscriber'),
        ('chats', '0007_alter_answercomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_conversation_answers', to='chats.commentconversation', verbose_name='Комметрарий'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_conversations_answers', to='profile.profile', verbose_name='Автор ответа'),
        ),
        migrations.AlterField(
            model_name='commentconversation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_conversations_comments', to='profile.profile', verbose_name='Автор комментария'),
        ),
    ]
