# Generated by Django 4.2.2 on 2023-08-11 09:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_answercomment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='commentconversation',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='commentconversation',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='commentconversation',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='conversationpost',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст'),
        ),
    ]
