# Generated by Django 4.2.2 on 2023-08-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_answercomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationpost',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пост беседки', 'verbose_name_plural': 'Посты беседки'},
        ),
        migrations.DeleteModel(
            name='AnswerComment',
        ),
    ]
