# Generated by Django 4.2.2 on 2023-08-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_conversationpost_options_delete_answercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentconversation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.commentconversation', verbose_name='Корневой комментарий'),
        ),
        migrations.AddField(
            model_name='conversationpost',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
