# Generated by Django 4.2.2 on 2023-08-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_commentconversation_parent_conversationpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentconversation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='chats.commentconversation', verbose_name='Корневой комментарий'),
        ),
    ]
