# Generated by Django 4.2.2 on 2023-08-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_alter_commentconversation_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentconversation',
            options={'ordering': ('-created_at',), 'verbose_name': 'Комметарий', 'verbose_name_plural': 'Комметарии'},
        ),
    ]
