# Generated by Django 4.2.2 on 2023-08-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_alter_commentconversation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
