# Generated by Django 4.2.2 on 2023-08-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_chat_options_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecomment',
            old_name='photo',
            new_name='image',
        ),
    ]
