# Generated by Django 4.2.2 on 2023-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='status_watermark',
            field=models.BooleanField(default=False, verbose_name='Необходим копирайт'),
        ),
    ]
