# Generated by Django 4.2.2 on 2023-08-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0017_imagepost_status_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название чата'),
        ),
    ]
