# Generated by Django 4.2.2 on 2023-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_series_logo'),
        ('chats', '0020_alter_message_chat_alter_message_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpost',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='conversation_tags', to='products.tag', verbose_name='Теги'),
        ),
    ]
