# Generated by Django 4.2.2 on 2023-07-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_merge_20230718_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('text_appeal', models.CharField(max_length=255, verbose_name='Текст обращения')),
                ('description', models.TextField(blank=True, verbose_name='Описание программы')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название комплекса')),
                ('recommendation', models.TextField(blank=True, max_length=255, verbose_name='Описание рекомендаций')),
                ('products', models.ManyToManyField(related_name='complexes', to='products.product', verbose_name='Продукты')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='program_complexes', to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Комплекс',
                'verbose_name_plural': 'Комплексы',
            },
        ),
    ]
