# Generated by Django 4.2.2 on 2023-08-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_complexes', to='programs.program', verbose_name='Программа'),
        ),
    ]
