# Generated by Django 4.2.2 on 2023-12-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_complex_products_remove_program_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programresult',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='programresult',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание Программы'),
        ),
    ]
