# Generated by Django 4.2.2 on 2023-06-28 15:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='label')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
    ]
