# Generated by Django 4.2.2 on 2023-06-28 16:02

from django.db import migrations
from django_countries import countries


def forwards_func(apps, schema_editor):
    Country = apps.get_model('settings', 'Country')

    countries_list = []
    for code, name in countries:
        countries_list.append(Country(country=code, label=name))

    Country.objects.bulk_create(countries_list, batch_size=100, ignore_conflicts=True)


def reverse_func(apps, schema_editor):
    Country = apps.get_model('settings', 'Country')
    Country.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
