# Generated by Django 4.2.2 on 2023-09-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20230628_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(max_length=300, verbose_name='Причина блокировки')),
            ],
        ),
    ]
