# Generated by Django 4.2.2 on 2023-10-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_socialweb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialweb',
            name='logo',
        ),
    ]
