# Generated by Django 4.2.2 on 2023-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_socialweb_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialweb',
            name='logo',
            field=models.FileField(default=1, upload_to='social/logo/', verbose_name='Лого'),
            preserve_default=False,
        ),
    ]
