# Generated by Django 4.2.2 on 2023-11-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_socialweb_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип волос',
                'verbose_name_plural': 'Типы волос',
            },
        ),
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип кожи',
                'verbose_name_plural': 'Типы кожи',
            },
        ),
    ]
