# Generated by Django 4.2.2 on 2023-07-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontest',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Один подходящий ответ'), (1, 'Множественный выбор'), (2, 'Свободная форма ответа')], verbose_name='Тип ответа'),
        ),
    ]
