# Generated by Django 4.2.2 on 2023-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_questiontest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Вариант ответа'),
        ),
    ]
