# Generated by Django 4.2.2 on 2023-07-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_answerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='testing.test', verbose_name='Тест'),
        ),
    ]
