# Generated by Django 4.2.2 on 2023-07-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_answer_product_alter_answer_question_and_more'),
        ('testing', '0006_alter_questiontest_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerprofile',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AddField(
            model_name='answerprofile',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.questiontest', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answerprofile',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='testing.choice', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answerprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_test_answers', to='profile.profile', verbose_name='Профиль'),
        ),
    ]
