# Generated by Django 4.2.2 on 2023-07-19 09:49

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_alter_answerprofile_options_answerprofile_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.tools.database_operations.CleanImageField(upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_images', to='testing.choice', verbose_name='Вариант ответа')),
            ],
        ),
    ]
