# Generated by Django 4.2.2 on 2023-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_imagechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ответа'),
        ),
        migrations.AddField(
            model_name='questiontest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание вопроса'),
        ),
    ]
