# Generated by Django 4.2.2 on 2023-07-19 09:51

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_choice_description_questiontest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagechoice',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_images', to='testing.choice', verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='imagechoice',
            name='image',
            field=apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка'),
        ),
    ]
