# Generated by Django 4.2.2 on 2023-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_alter_imagechoice_choice_alter_imagechoice_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerprofile',
            name='choice',
        ),
        migrations.AddField(
            model_name='answerprofile',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice_answers', to='testing.choice', verbose_name='Ответы'),
        ),
    ]
