# Generated by Django 4.2.2 on 2023-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_remove_answerprofile_choice_answerprofile_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerprofile',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answerprofile',
            name='choice',
            field=models.ManyToManyField(blank=True, related_name='choice_answers', to='testing.choice', verbose_name='Выбранные ответы'),
        ),
    ]
