# Generated by Django 4.2.2 on 2023-07-19 11:22

import apps.tools.database_operations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('testing', '0013_alter_questiontest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.tools.database_operations.CleanImageField(blank=True, null=True, upload_to=apps.tools.database_operations.CleanImageField.get_image_path, verbose_name='Картинка')),
            ],
        ),
        migrations.RenameField(
            model_name='answerprofile',
            old_name='choice',
            new_name='option',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='Option',
        ),
        migrations.DeleteModel(
            name='ImageChoice',
        ),
        migrations.AddField(
            model_name='imageoption',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_images', to='testing.option', verbose_name='Вариант ответа'),
        ),
    ]
