# Generated by Django 4.2.2 on 2023-07-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_imageoption_rename_choice_answerprofile_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontest',
            name='type',
            field=models.CharField(choices=[('one', 'Один подходящий ответ'), ('many', 'Множественный выбор'), ('text', 'Свободная форма ответа')], max_length=15, verbose_name='Тип ответа'),
        ),
    ]
