# Generated by Django 4.2.2 on 2023-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_test_created_at_test_is_publish_test_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontest',
            name='type',
            field=models.CharField(choices=[('ONE', 'Один подходящий ответ'), ('MANY', 'Множественный выбор'), ('TEXT', 'Булевый тип ответа (да/нет)'), ('BOOL', 'Свободная форма ответа')], max_length=15, verbose_name='Тип ответа'),
        ),
    ]
