# Generated by Django 4.2.2 on 2023-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_alter_test_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontest',
            name='type',
            field=models.CharField(choices=[('ONE', 'Один подходящий ответ'), ('MANY', 'Множественный выбор'), ('BOOL', 'Булевый тип ответа (да/нет)'), ('TEXT', 'Свободная форма ответа')], max_length=15, verbose_name='Тип ответа'),
        ),
    ]
