# Generated by Django 4.2.2 on 2023-07-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_category_remove_product_group_and_more'),
        ('catalog', '0002_alter_category_group_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='CatalogGroup',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
