# Generated by Django 4.2.2 on 2023-07-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0007_alter_answer_product_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название подбора')),
            ],
            options={
                'verbose_name': 'Подбор',
                'verbose_name_plural': 'Подборы',
            },
        ),
        migrations.CreateModel(
            name='QuestionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('one', 'Один подходящий ответ'), ('many', 'Множественный выбор'), ('text', 'Свободная форма ответа')], max_length=15, verbose_name='Тип ответа')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вопроса')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_questions', to='selection.selection', verbose_name='Подбор')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Вариант ответа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_selection_options', to='selection.questionselection', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='AnswerSelectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('option', models.ManyToManyField(blank=True, related_name='option_selection_answers', to='selection.option', verbose_name='Выбранные ответы')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_selection_answers', to='profile.profile', verbose_name='Профиль')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.questionselection', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
