# Generated by Django 4.2.2 on 2023-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_rename_option_optionselection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionselection',
            name='type',
            field=models.CharField(choices=[('one', 'Один подходящий ответ'), ('many', 'Множественный выбор'), ('bool', 'Булевый тип ответа (да/нет)'), ('text', 'Свободная форма ответа')], max_length=15, verbose_name='Тип ответа'),
        ),
    ]
