# Generated by Django 4.2.2 on 2023-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_alter_questionselection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='selection',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
