# Generated by Django 4.2.2 on 2023-07-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_selection_created_at_selection_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
