# Generated by Django 4.2.2 on 2023-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_alter_questionselection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название теста'),
        ),
    ]
