# Generated by Django 4.2.2 on 2023-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_alter_selection_created_at_alter_selection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
